insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ukraine', 'Kivsharivka', 'UAH');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Iran', 'Māmūnīyeh', 'IRR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Beiyang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Kazakhstan', 'Atbasar', 'KZT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Gagah', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Jurak Lao’', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Mollepampa', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Spain', 'Santander', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Dolice', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Pakistan', 'Khāngāh Dogrān', 'PKR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Turpo', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Iran', 'Kalāleh', 'IRR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Gangshangji', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Mexico', 'Ejidal', 'MXN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ireland', 'Adare', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Huangcun', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Diaoling', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Armação de Búzios', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Mölndal', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Wielka Nieszawka', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Yemen', '‘Ubāl', 'YER');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Cape Verde', 'Ponta do Sol', 'CVE');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Bogotá', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Malbug', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Nigeria', 'Obolo-Eke (1)', 'NGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Sarrat', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Miaoshou', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Granja do Tedo', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Radovitskiy', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Josefův Důl', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Montelíbano', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Tagasilay', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Pengdian', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Netherlands', 'Hoogeveen', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Shawnee Mission', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Myanmar', 'Minbu', 'MMK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Genisséa', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Washington', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Angola', 'Lobito', 'AOA');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Sangojar', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Paclolo', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Örebro', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Jieshipu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Karang Kulon', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Yongqin', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Myanmar', 'Yamethin', 'MMK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Zbraslav', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Povarovo', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Uchkulan', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Sobreira', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Bandhagen', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Richmond', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Wichita', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Morocco', 'Zagora', 'MAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Passagem', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'San Buenaventura', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Nigeria', 'Zuru', 'NGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Kazakhstan', 'Ognevka', 'KZT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Deqing', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Yangxiang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Nicaragua', 'San Rafael del Sur', 'NIO');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sierra Leone', 'Segbwema', 'SLL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Vyksa', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Zengtian', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Pakisrejo', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Shaxi', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Mongaguá', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Escola', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Tyresö', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Tanzania', 'Puma', 'TZS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Huarong', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Poiares', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Wentai', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Algarrobo', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Mauritania', 'Tékane', 'MRO');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Libertad', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Conima', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Karatsu', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Vale Mourão', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Nice', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Keda', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Vietnam', 'Cẩm Phả Mines', 'VND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Hekou', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Tomelilla', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Malawi', 'Rumphi', 'MWK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Azerbaijan', 'Lökbatan', 'AZN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'South Africa', 'KwaMbonambi', 'ZAR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Recarei', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Morocco', 'Sidi Smaïl', 'MAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Guam', 'Santa Rita Village', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Malaysia', 'Kuala Lumpur', 'MYR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Timbó', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Pakistan', 'Nankāna Sāhib', 'PKR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Antigua and Barbuda', 'Liberta', 'XCD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Rezé', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Sosándra', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Trinidad and Tobago', 'Tabaquite', 'TTD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Skinnskatteberg', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Suidong', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Kurihashi', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Turkey', 'Merkezköy', 'TRY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Valence', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Rockford', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Bombon', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Malpique', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Mexico', 'San Francisco', 'MXN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Pahing Pamulihan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Lithuania', 'Širvintos', 'LTL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Iran', 'Fūman', 'IRR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ireland', 'Dunlewy', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Kanoya', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Mongolia', 'Buyant', 'MNT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ukraine', 'Kostryzhivka', 'UAH');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Shiki', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Shanghu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Ribeiro', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Vietnam', 'Một Ngàn', 'VND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Timbó', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Laotai', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Albania', 'Dushk', 'ALL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Abade de Vermoim', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'South Africa', 'Pofadder', 'ZAR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Rochester', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Nigeria', 'Musawa', 'NGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Tambakmerak', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Poxi', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Coutances', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Balitai', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Klagen', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Saint Cloud', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Saint Lucia', 'Canaries', 'XCD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Cibunar', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Dominican Republic', 'Laguna Salada', 'DOP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Muzidian', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Zábřeh', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Hungary', 'Tatabánya', 'HUF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Krasnokholm', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Armenia', 'Vardenik', 'AMD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Caen', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Karpokhórion', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Estonia', 'Viljandi', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Thailand', 'Phu Luang', 'THB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Shreveport', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Sanzhang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Banjar Anyar', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Unden', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Legionowo', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Gerelayang', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Bosnia and Herzegovina', 'Ostrožac', 'BAM');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Alpedrinha', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Slovenia', 'Ljubno ob Savinji', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Liudaogou', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Baimiao', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Bankaw', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Yalukou', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Tōkamachi', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Coronel Suárez', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Ayo', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Changlu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Huntington', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'San Javier', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Armenia', 'Geghanist', 'AMD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Kablukan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Funza', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'La Unión', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Davila', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Honduras', 'San Vicente Centenario', 'HNL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Thailand', 'Wang Chan', 'THB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Seč', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Denmark', 'København', 'DKK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Bronnitsy', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Volgodonsk', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Rimbo', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Setúbal', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Afghanistan', 'Qal‘ah-ye Fārsī', 'AFN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Mishima', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Malaysia', 'Kuala Terengganu', 'MYR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Kobeřice', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Luzino', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xiayang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Doña Remedios Trinidad', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Banjaranyar', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Vanderhoof', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Chad', 'Mboursou Léré', 'XAF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Sarreguemines', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Awarawar', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'High Point', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Bai’e', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Macedonia', 'Липково', 'MKD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Damaying', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Croatia', 'Pitomača', 'HRK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Chumen', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Hungary', 'Debrecen', 'HUF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Hobonio', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Tyazhinskiy', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Iran', 'Qal‘eh Ganj', 'IRR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Changsheng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Duyang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Yuanping', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Benevides', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Mompós', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Chile', 'Paine', 'CLP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Duzhenwan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Italy', 'Roma', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Yaransk', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Quintã', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Sainte-Agathe-des-Monts', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Bulgaria', 'Levski', 'BGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Aegela', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xincheng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Mungging', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Monte de Trigo', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Gucheng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Colinas', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Ponjen', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Kazakhstan', 'Balqash', 'KZT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Yahe', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Serbia', 'Uzdin', 'RSD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Cibalung', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Tubalan', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Vilarinho das Cambas', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Hungary', 'Pápa', 'HUF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Ponta Porã', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xindong', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Uzbekistan', 'Oqtosh', 'UZS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Taganak', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xujiadian', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Raduzhnyy', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Pakistan', 'Talhār', 'PKR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Bolivia', 'Limoncito', 'BOB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Slovenia', 'Tabor', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Libya', 'Murzuq', 'LYD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Zama', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Gambia', 'Bureng', 'GMD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ukraine', 'Krasyliv', 'UAH');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Vietnam', 'Vũ Thư', 'VND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'South Africa', 'Ficksburg', 'ZAR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Carmen', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Sukomulyo', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Nigeria', 'Isanlu Itedoijowa', 'NGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Thailand', 'Hang Dong', 'THB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Radomin', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Sanxing', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Ciracap', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Cisoka', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Vilar do Pinheiro', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Denmark', 'Frederiksberg', 'DKK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Vietnam', 'Krông Kmar', 'VND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Lyon', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Jengglungharjo', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xinjie', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xinmin', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Pakistan', 'Mātli', 'PKR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Muara', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Malawi', 'Machinga', 'MWK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Chile', 'Taltal', 'CLP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Martensville', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Afghanistan', 'Ţāqchah Khānah', 'AFN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Banjar Batanpoh', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Amieirinha', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Libertad', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Lewopao', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Pasirhuni', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Netherlands', 'Waalwijk', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Hägersten', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Bagjasari', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Dongshentou', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Nigeria', 'Ibadan', 'NGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Kallífytos', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Yemen', 'Al Madīd', 'YER');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Venezuela', 'Irapa', 'VEF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Campelos', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Pasonobenu', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Sussex', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Guam', 'Asan-Maina Village', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Banjar Kelodan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ireland', 'Sallins', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Thailand', 'Ban Huai Thalaeng', 'THB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Lithuania', 'Nida', 'LTL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Esquina', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Eritrea', 'Teseney', 'ERN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Itapira', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Namibia', 'Bethanie', 'NAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Sangpi', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Biyong', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Zuitou', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'La Rochelle', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Perm', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Heshan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Turkmenistan', 'Gowurdak', 'TMT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Kuala Bintang', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Vietnam', 'Quận Mười', 'VND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Poshekhon’ye', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Täby', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Costa Rica', 'Pital', 'CRC');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Izmaylovo', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Campos Sales', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Savannah', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Bell Ville', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Honduras', 'Yuscarán', 'HNL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Ancahuasi', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Yemen', 'Al Ḩayfah', 'YER');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Zhangjiachang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Sagana', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Taurisma', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ukraine', 'Tysmenychany', 'UAH');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Takeo', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Tunisia', 'Rohia', 'TND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Changle', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Irasan', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Coaticook', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Niulanshan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Nigeria', 'Kuje', 'NGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Qian’an', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Ōtsuchi', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Austria', 'Wolfsberg', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Qiewa', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Sabugueiro', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Terentang', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Vietnam', 'Bến Cầu', 'VND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Pakistan', 'Garhi Yāsīn', 'PKR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Mexico', 'Independencia', 'MXN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'New Zealand', 'Christchurch', 'NZD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xingfu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Laguna Paiva', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Bengubelan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Noda', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Cabadiangan', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Uganda', 'Kole', 'UGX');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Hukeng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Finland', 'Vilppula', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Thailand', 'Nong Bua', 'THB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Barão de Melgaço', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'New Zealand', 'Whakatane', 'NZD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Ciénaga de Oro', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Elena', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Ōtsuki', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Herval', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Portelândia', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Serbia', 'Lebane', 'RSD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Taekas', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Tournavista', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Sacotes', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Quinta da Queimada', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Uganda', 'Yumbe', 'UGX');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Bandung', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Knyaze-Volkonskoye', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Norway', 'Oslo', 'NOK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Malaysia', 'Melaka', 'MYR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Ilhéus', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Santa Marta de Penaguião', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Detchino', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Tiehe', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Nepomuceno', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Reunion', 'Saint-Denis', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Doubrava', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Kabare', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Shanxia', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Hungary', 'Szeged', 'HUF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Bogoria', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Pepayan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'San Jose', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Ibagué', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'South Korea', 'Ganghwa-gun', 'KRW');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Little Baguio', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Huzhuang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Larap', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Lijiapu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Kalangbret', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Turkmenistan', 'Balkanabat', 'TMT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Meilin', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Kalinovskaya', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Taochuan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Deep River', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Cuba', 'Cifuentes', 'CUP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Azerbaijan', 'Khirdalan', 'AZN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Peru', 'Chumpi', 'PEN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Toki', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Kansas City', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Yemen', '‘Abs', 'YER');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Saint Lucia', 'Micoud', 'XCD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Iran', 'Kabūdarāhang', 'IRR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Huicheng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Germany', 'Berlin', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Cikiruh Wetan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Grzmiąca', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Várzea de Sintra', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Pappádos', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Dahuaishu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Wasquehal', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Caeté', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Dinaig', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Huayuan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Río Segundo', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'San Carlos', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'North Korea', 'Chongjin', 'KPW');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Majennang', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Bantar Tengah', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Nishio', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'San Rafael', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Babakan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Staryy Urukh', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xianxiang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Chengxiang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Bryukhovetskaya', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Chegdomyn', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Honduras', 'La Libertad', 'HNL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Stockholm', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Gaibei', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Baiyin', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Zhengji', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Amarillo', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Madagascar', 'Bealanana', 'MGA');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'San Eduardo', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Jagabaya Dua', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Mexico', 'San Juan', 'MXN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Tanzania', 'Liwale', 'TZS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Kushelevka', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Colombo', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Lewoluo', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Nanterre', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Netherlands', 'Emmen', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Norway', 'Kristiansund N', 'NOK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Turki', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Sarangmeduro', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Sambongmulyo', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Serbia', 'Ćićevac', 'RSD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Panama', 'Palmira', 'PAB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Pitanga', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Neiguan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Angered', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United Kingdom', 'West End', 'GBP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Campos do Jordão', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'San Rafael', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Bima', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Baofeng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Daciyao', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Tibakisa', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Kurume', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Kazakhstan', 'Zhanaozen', 'KZT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Quintas', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Cherga', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Libu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Cuba', 'Venezuela', 'CUP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Lebanon', 'El Hermel', 'LBP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Mexico', 'Independencia', 'MXN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Romba', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Kanghe', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Afghanistan', 'Ghazni', 'AFN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ethiopia', 'Mendī', 'ETB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xishui', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Sannikovo', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Tuwa', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Kos', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Kroczyce', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Armenia', 'Astghadzor', 'AMD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Xilópolis', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Nangkapayung', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Croatia', 'Lipovljani', 'HRK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Zambia', 'Kasempa', 'ZMW');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Cameroon', 'Bogo', 'XAF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Karlskoga', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Luxembourg', 'Boulaide', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Garwolin', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Nelazskoye', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Poteran', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Toulouse', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ukraine', 'Obukhiv', 'UAH');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Malaysia', 'Kuala Lumpur', 'MYR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Urung', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Tunisia', 'Majāz al Bāb', 'TND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Malé Svatoňovice', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Honglan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Vietnam', 'Đắk Song', 'VND');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xinxu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Xinxing', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Sancha', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Hecheng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Lushan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Ibaiti', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Clearwater', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Peredovaya', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Tabogon', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'General Arenales', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Temuji', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Payabon', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Tuanshansi', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Lipu', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Warugunung', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Afghanistan', 'Mazār-e Sharīf', 'AFN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Shubenka', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Weetombo', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Palestinian Territory', 'Arţās', 'ILS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Příbor', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'San Carlos de Bolívar', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Beiping', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Silihe', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Venezuela', 'Yaguaraparo', 'VEF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Uruguay', 'Punta del Este', 'UYU');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Ganggawang', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'São Sebastião', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Shuanglong', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Sidomulyo', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Rostov-na-Donu', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Croatia', 'Šenkovec', 'HRK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Damawato', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Ruteng', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Costa Rica', 'Alajuela', 'CRC');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Sugito', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Czech Republic', 'Staré Křečany', 'CZK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Belarus', 'Kosava', 'BYR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Watrous', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Finland', 'Otaniemi', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Bełk', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Huerta Grande', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Gemo', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ecuador', 'Puerto Francisco de Orellana', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Pasanggrahan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Villa Bustos', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Arvidsjaur', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Anan', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Ermelo', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Denmark', 'København', 'DKK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Nanqi', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Stryszów', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Japan', 'Shinshiro', 'JPY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Kalpin', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Bulgaria', 'Zlataritsa', 'BGN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Colombia', 'Soledad', 'COP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Jabłonica Polska', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Jamaica', 'Portmore', 'JMD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Medellin', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Umeå', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Nevel’', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Palestinian Territory', 'Kafr Zībād', 'ILS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Harbin', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Zimbabwe', 'Raffingora', 'ZWL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Pindaré Mirim', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Bermuda', 'Hamilton', 'BMD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Mabini', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Kazakhstan', 'Zhanaozen', 'KZT');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Belozërsk', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Spain', 'Cartagena', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Venezuela', 'El Corozo', 'VEF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Nanguzhuang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Jinshan', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Loudi', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'United States', 'Topeka', 'USD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Norway', 'Oslo', 'NOK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Val-de-Reuil', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Luleå', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Luxembourg', 'Mondorf-les-Bains', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Luxembourg', 'Müllendorf', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'French Polynesia', 'Vaitape', 'XPF');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Croatia', 'Predavac', 'HRK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Saint Lucia', 'Micoud', 'XCD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Béziers', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Krasnovishersk', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Lewisporte', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Margoyoso', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Rybczewice', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Poland', 'Jadowniki', 'PLN');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Pagsañgahan', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ukraine', 'Ichnya', 'UAH');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Béziers', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Yemen', 'Şuwayr', 'YER');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Covas', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Zhizhong', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Shentang', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'France', 'Rennes', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Nongba', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Canada', 'Norfolk County', 'CAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Villa Urquiza', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Changzheng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Ireland', 'Clonskeagh', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Hudong', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Tanzania', 'Uyovu', 'TZS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Beringinjaya', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Portugal', 'Ribeira', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Elekmonar', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Morocco', 'Sidi Qacem', 'MAD');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Greece', 'Árgos', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Spain', 'Almeria', 'EUR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Wuku', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Ivoti', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Yong’an', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Philippines', 'Tapas', 'PHP');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Nizhnyaya Maktama', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Puqi', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Brazil', 'Itapagé', 'BRL');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Thailand', 'Non Sang', 'THB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Argentina', 'Colonias Unidas', 'ARS');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Gaocheng', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Indonesia', 'Trambalan', 'IDR');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Sweden', 'Sunne', 'SEK');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Hengshui', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Russia', 'Vatutino', 'RUB');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Taiyangling', 'CNY');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'Guatemala', 'Pochuta', 'GTQ');
insert into lugares (id, pais, ciudad, divisa) values (lugares_id_seq.NEXTVAL, 'China', 'Yantian', 'CNY');
