insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '2771053209', 1);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '4541731959', 2);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '5966753083', 3);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '0276483944', 4);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '4821063859', 5);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Corriente', '8009634301', 6);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '5153790886', 7);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '8591121333', 8);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '2286699283', 9);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '9629455358', 10);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Ahorros', '5832094395', 11);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '0828903050', 12);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '6572877558', 13);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '1409320456', 14);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '0462655482', 15);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Corriente', '8193786491', 16);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Corriente', '3675516180', 17);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '6530759549', 18);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Corriente', '6024618972', 19);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '6600881003', 20);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Corriente', '4553089386', 21);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '5150819549', 22);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '5824497494', 23);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '0082898790', 24);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '8374510382', 25);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Ahorros', '9081269852', 26);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '2975728999', 27);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Corriente', '6351514398', 28);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '9757132780', 29);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '0627224067', 30);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Ahorros', '0367457458', 31);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '6753918949', 32);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '4605631399', 33);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '0043918018', 34);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '9852808230', 35);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '0393254704', 36);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '3561701574', 37);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '8505219554', 38);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '8593753787', 39);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '8501462438', 40);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '9478011626', 41);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '2686159049', 42);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Corriente', '4612962249', 43);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Ahorros', '2710508559', 44);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '1078795282', 45);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '2897225122', 46);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Corriente', '0424726475', 47);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '0863508677', 48);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Corriente', '3192499087', 49);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Corriente', '1089903375', 50);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Ahorros', '1742080820', 51);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '4482347469', 52);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '0611747707', 53);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '9751199433', 54);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '8461629965', 55);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '5936444279', 56);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Corriente', '7669564350', 57);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '8514440268', 58);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '2827058839', 59);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '4891085150', 60);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '4907510373', 61);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '8063391985', 62);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '0384678475', 63);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Corriente', '9878580229', 64);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Ahorros', '3119502286', 65);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '0509918891', 66);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '0220897018', 67);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Corriente', '4305406500', 68);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '4272460498', 69);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '2730303960', 70);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Corriente', '8723840420', 71);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '7495494433', 72);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '3265788806', 73);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '2772344290', 74);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '5823026447', 75);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '1261231880', 76);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '3988302430', 77);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '5448301363', 78);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '7528809071', 79);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '7939068512', 80);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Corriente', '9692182185', 81);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '3597165427', 82);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Corriente', '1218242868', 83);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '9598749304', 84);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '8191988402', 85);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '5568759677', 86);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '6190884377', 87);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Corriente', '2176979443', 88);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Corriente', '8245379336', 89);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Corriente', '6524385969', 90);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Ahorros', '3510057880', 91);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Davivienda', 'Ahorros', '8110425933', 92);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '4693593206', 93);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco de Bogota', 'Corriente', '2960233778', 94);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Banco Popular', 'Ahorros', '2697419470', 95);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Avvillas', 'Ahorros', '4935728361', 96);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Corriente', '2896330054', 97);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bancolombia', 'Ahorros', '7537522820', 98);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'Bank of America', 'Ahorros', '8055595313', 99);
insert into metodos_pago_conductores (id, banco, tipo_cuenta, cuenta, usuario_id) values (meto_pag_conduc_id_seq.NEXTVAL, 'BBVA', 'Corriente', '7197574781', 100);
