insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'MTD-527', 'Eagle', 'Talon', 1991);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'BCT-874', 'Kia', 'Rio', 2002);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'KUC-795', 'Lincoln', 'Continental', 1988);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'DVA-563', 'Lincoln', 'Navigator', 2000);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'XJC-805', 'Volkswagen', 'Scirocco', 1985);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'RAD-869', 'Oldsmobile', 'Cutlass Supreme', 1994);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'DGY-081', 'Ford', 'Crown Victoria', 2002);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'MTL-048', 'Saturn', 'Outlook', 2007);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'KOO-391', 'Toyota', 'Tundra', 2009);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'UCS-177', 'Volkswagen', 'GTI', 1988);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'PWX-559', 'Nissan', 'Titan', 2011);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'ZNM-745', 'Suzuki', 'Vitara', 2003);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'KSU-956', 'Nissan', 'Pathfinder', 2003);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'BFC-425', 'Chevrolet', 'TrailBlazer', 2005);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'DQW-799', 'Eagle', 'Summit', 1995);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'PVI-745', 'Mercury', 'Monterey', 2004);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'OFR-707', 'Nissan', 'GT-R', 2013);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'LXI-134', 'Jaguar', 'S-Type', 2004);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'QOB-808', 'Subaru', 'Baja', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'YAR-529', 'Subaru', 'Legacy', 1995);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'OSD-241', 'Volkswagen', 'Passat', 2003);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'HVI-812', 'Chrysler', 'LeBaron', 1993);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'LAB-979', 'Land Rover', 'Discovery', 1994);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'IXN-982', 'Ford', 'Taurus', 2008);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'EBQ-866', 'Ford', 'Club Wagon', 1996);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'ZAF-479', 'Ford', 'Explorer Sport Trac', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'LDL-809', 'Dodge', 'Ram Van 2500', 1999);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'DGZ-489', 'Ford', 'Ranger', 1996);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'BTW-205', 'Ford', 'Escort', 1997);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'HZC-375', 'Dodge', 'Intrepid', 1999);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'AWH-545', 'Chrysler', 'Sebring', 2009);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'EOK-710', 'Toyota', 'Matrix', 2005);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'FJA-084', 'BMW', '6 Series', 2007);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'KKU-353', 'Toyota', 'Camry', 2010);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'SPY-449', 'Chevrolet', 'Avalanche', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'OQF-664', 'Honda', 'Insight', 2011);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'IAX-701', 'Maybach', '57', 2005);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'ELN-322', 'Volvo', 'C30', 2012);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'PRU-526', 'Cadillac', 'Seville', 1995);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'RWT-474', 'Saturn', 'S-Series', 2001);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'UDD-163', 'Mazda', 'Mazdaspeed 3', 2012);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'RUF-222', 'Toyota', 'Tercel', 1993);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'TDM-809', 'Nissan', 'Sentra', 1992);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'VNY-558', 'GMC', 'Savana 1500', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'YRT-553', 'Jeep', 'Grand Cherokee', 2011);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'KJS-714', 'Cadillac', 'DTS', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'BBM-433', 'Dodge', 'Dakota Club', 1997);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'XXS-899', 'Honda', 'Odyssey', 2002);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'BCH-777', 'Mitsubishi', 'Galant', 1998);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'NXG-424', 'Bentley', 'Continental Flying Spur', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'WZN-404', 'Saab', '900', 1991);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'BKP-631', 'Lincoln', 'LS', 2005);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'LDN-771', 'Mercedes-Benz', 'E-Class', 1989);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'IRR-837', 'Plymouth', 'Sundance', 1994);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'ARV-600', 'Isuzu', 'Ascender', 2003);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'LHC-183', 'Saab', '9-5', 2004);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'QNK-834', 'Infiniti', 'Q', 1995);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'IBL-873', 'Nissan', 'Pathfinder', 2003);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'KNX-676', 'Honda', 'Odyssey', 2002);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'QUH-275', 'Infiniti', 'Q', 2005);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'FJB-354', 'GMC', 'Vandura 1500', 1994);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'YWX-421', 'Mazda', 'MX-5', 2012);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'GJH-751', 'GMC', 'Sierra', 2009);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'ORF-547', 'Chevrolet', 'Express 2500', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'YSG-017', 'GMC', '2500 Club Coupe', 1996);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'PDW-126', 'Toyota', 'Ipsum', 2000);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'PRE-167', 'Honda', 'Accord', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'JAW-892', 'GMC', 'Jimmy', 2001);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'FLT-758', 'Oldsmobile', 'Aurora', 2001);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'XGJ-904', 'Mitsubishi', 'Pajero', 1994);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'AZT-936', 'Mazda', 'B-Series Plus', 1996);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'SJB-140', 'Lincoln', 'Continental', 2002);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'MTN-873', 'Kia', 'Sedona', 2008);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'TFH-770', 'BMW', '3 Series', 2003);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'IDX-792', 'Ford', 'F350', 1997);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'FJU-366', 'Mazda', 'Mazda6', 2007);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'ABC-261', 'Pontiac', 'Sunbird', 1994);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'YIX-977', 'Volkswagen', 'Golf', 2006);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'DBP-483', 'Chevrolet', 'Avalanche', 2007);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'JWU-057', 'Jaguar', 'XK Series', 2000);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'VOD-543', 'Mercedes-Benz', '300CE', 1993);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'HDH-200', 'Buick', 'Park Avenue', 1992);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'FID-691', 'Mitsubishi', 'Pajero', 1989);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'EYJ-056', 'Subaru', 'Legacy', 1993);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'QRX-536', 'Mercedes-Benz', 'E-Class', 1990);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'CKJ-972', 'BMW', '645', 2005);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'IJB-061', 'Pontiac', 'Firebird', 1994);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'USD-613', 'Mazda', 'MPV', 2002);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'HJP-191', 'GMC', 'Suburban 2500', 1993);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'CCG-978', 'Mazda', '929', 1989);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'ZUB-874', 'Kia', 'Optima', 2012);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'DWT-696', 'Chevrolet', 'Impala', 2002);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'JDI-977', 'Lincoln', 'Mark VIII', 1997);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'CBX-524', 'Citroën', '2CV', 1948);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'LVT-212', 'Dodge', 'Dakota', 1992);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'SUR-939', 'GMC', 'Savana 2500', 1998);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'VSB-584', 'Mazda', 'MX-5', 1991);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'PUK-358', 'Volvo', '940', 1992);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'IGM-823', 'Dodge', 'Charger', 2011);
insert into vehiculos (id, placa, marca, modelo, year) values (vehiculos_id_seq.NEXTVAL, 'FJC-102', 'Mitsubishi', 'Montero Sport', 2003);
